#!/bin/bash
#==========================================
#Name:isohub
#Autor:h0lik@linux
#GitHub:github.com/h0lik
#WebSite:https://soraxlab.ru
#Date:23.09.2024
#==========================================
source /opt/srvtools/isohub/lib/evn-lib
green='\e[32m'
blue='\e[34m'
clear='\e[0m'
ColorGreen(){
	echo -ne $green$1$clear
}
ColorBlue(){
	echo -ne $blue$1$clear
}
alma8() {
	cd $pool
	sudo wget  https://repo.almalinux.org/almalinux/8.10/isos/x86_64/AlmaLinux-8.10-x86_64-minimal.iso
	echo -e "Downloaded AlmaLinux-8 \e[32m successfully! \e[0m"
	echo -e "SHA-256 -> \e[32m fc866e1280e7b3f066b1380e831e33e7f3e78bc9db7bfc27744d569eadd974b3 \e[0m"
}
alma9() {
	cd $pool
	sudo wget https://repo.almalinux.org/almalinux/9.4/isos/x86_64/AlmaLinux-9-latest-x86_64-minimal.iso
	echo -e "Downloaded AlmaLinux-9 \e[32m successfully! \e[0m"
	echo -e "SHA-256 \e[32m 6624593b53c89195f7b68b2070a280d47b4276a7cbc10d2216661bf35d4f442b \e[0m"
}

menu_alma() {
echo -ne "
Distribution List
$(ColorGreen '1)') Alma Linux-8
$(ColorGreen '2)') Alma Linux-9
$(ColorGreen '0)') exit
$(ColorBlue 'Choose a distribution:') "
        read a
        case $a in
	        1) alma8 ; menu_alma ;;
	        2) alma9 ; menu_alma ;;
			0) exit 0 ;;
			*) echo -e $red"Wrong option."$clear; WrongCommand;;
        esac
}